### ISSUE TITLE
“Hello, could you please place the title and the link to the paper above?”

### ISSUE THREAD

**Issue by yydsok** [CheesyFrappe/Prompting-LLMs-for-Aerial-Navigation#1]

**Comment by BashMocha** [comment]
Hey, 

We appreciate your interest in our study. The paper has been accepted but has not been presented at the conference yet. 

The [conference](https://ubmk.org.tr/en/) will take place on October 26-28 and the paper will be published afterward with the title "**Prompting Large Language Models for Aerial Navigation**".

The link to the paper and citation information will be added once it's published.

**Comment by BashMocha** [comment]
The paper was published in IEEE Xplore yesterday. The citation and link to the paper have been added to the README.md file.

I am closing this issue.
